Branch RB-1.4.40 mit trunk zusammengeführt

diff --git a/sbin/import_workstations b/sbin/import_workstations
--- a/sbin/import_workstations
+++ b/sbin/import_workstations
@@ -4,7 +4,7 @@
 #
 # Thomas Schmitt
 # <schmitt@lmz-bw.de>
-# 12.04.2008
+# 19.11.2008
 #
 
 # check for import_workstations lockfile
@@ -74,6 +74,8 @@ case "$imaging" in
 
 		echo | tee -a $TMPLOG
 		. $SCRIPTSDIR/wimport.sh | tee -a $TMPLOG
+		RC_ML=${PIPESTATUS[0]}
+		[ $RC_ML -ne 0 ] && RC=$RC_ML
 		;;
 
 	rembo)
@@ -90,6 +92,8 @@ case "$imaging" in
 
 		echo | tee -a $TMPLOG
 		. $SCRIPTSDIR/wimport.sh | tee -a $TMPLOG
+		RC_ML=${PIPESTATUS[0]}
+		[ $RC_ML -ne 0 ] && RC=$RC_ML
 
 		# run this script for the package mlscripts (alternative to myshn)
 		if [ -e "/usr/sbin/mlscripts-wsimport" ]
@@ -116,9 +120,9 @@ echo "Ending import workstations session at `date`" | tee -a $TMPLOG
 echo "#####################################################################" | tee -a $TMPLOG
 
 if [ $RC -ne 0 ]; then
-	echo
-	echo "Finished with error(s)! Please look at $LOGFILE! Detailed output will be mailed to $ADMINISTRATOR!"
-	cat $TMPLOG | mail -s "import_workstations finished with error" $ADMINISTRATOR@localhost
+	echo | tee -a $TMPLOG
+	echo "Finished with error(s)! Please look at $LOGFILE! Detailed output will be mailed to $ADMINISTRATOR!" | tee -a $TMPLOG
+	cat $TMPLOG | mail -s "import_workstations finished with error(s)!" $ADMINISTRATOR@localhost
 fi
 
 # append log
@@ -129,3 +133,4 @@ rm -f $TMPLOG
 rm -f $locker
 
 exit $RC
+
