* linuxmuster-setup:    - Cdrom-Handling bei Erstinstallation verbessert.    - obsolete Tivoli Konfigurationsvorlagen entfernt.  * eject zu Paketabhängigkeiten hinzugefügt.  * helperfunctions.sh:    - Funktion get_room_ip() hinzugefügt, gibt IP-Adresse eines Raums zurück.    - Funktion validhostname() hinzugefügt, prüft ob Hostnamen RFC 952 entsprechen.  * wimport.sh:    - Hostnamensprüfung verwendet nun validhostname() (schließt #245).    - Maschinepasswort wird nun für jeden Host gesetzt, nicht mehr nur für neue.  * import_printers: verwendet nun get_room_ip() um das Raumsubnetz zu ermitteln (schließt #244).  * paedml50-upgrade: entfernt nun /etc/apache2/conf.d/nagios2.conf.

diff --git a/sbin/linuxmuster-setup b/sbin/linuxmuster-setup
--- a/sbin/linuxmuster-setup
+++ b/sbin/linuxmuster-setup
@@ -97,10 +97,27 @@ case $opt in
     # add cyrus user
     id cyrus &> /dev/null || useradd -c "Cyrus Mailsystem User" -d /var/spool/cyrus -g mail -m -r -s /bin/sh cyrus | tee -a $logfile
 
-    # load cdrom tray
+    # mount cdrom
     if grep -q ^"deb cdrom" /etc/apt/sources.list; then
-	eject -t
-	mount /cdrom
+	eject -t &> /dev/null
+	for i in "" scd0 scd1 scd2; do
+	 if mount_cdrom "$i"; then
+	  if stringinstring scd "$i"; then
+	   rm -f /dev/cdrom /dev/dvd
+	   ln -s /dev/$i /dev/cdrom
+	   ln -s /dev/$i /dev/dvd
+	   cp /etc/fstab /etc/fstab.linuxmuster-setup.first
+	   grep -v cdrom /etc/fstab.linuxmuster-setup.first > /etc/fstab
+	   echo "/dev/$i /media/cdrom0 udf,iso9660 user,noauto 0 0" >> /etc/fstab
+	  fi
+	  cdrom_mounted=yes
+	  break
+	 fi
+	done
+	if [ -z "$cdrom_mounted" ]; then
+	 echo "Fatal: Cannot mount install cd!"
+	 exit 1
+	fi
     fi
 
     # install paedml release key
