linuxmuster-reset: Returncode-Handling und Konsolenausgabe verbessert.

diff --git a/sbin/linuxmuster-reset b/sbin/linuxmuster-reset
--- a/sbin/linuxmuster-reset
+++ b/sbin/linuxmuster-reset
@@ -4,7 +4,7 @@
 # resets the internet, intranet, webfilter, lession state of rooms/hosts
 #
 # thomas@linuxmuster.net
-# 27.01.2014
+# 28.01.2014
 # GPL V3
 #
 
@@ -26,7 +26,7 @@ exit_script() {
  local RC=1
  [ -n "$1" ] && RC="$1"
  echo | tee -a $LOGFILE
- echo "Ending linuxmuster-reset session at `date`" | tee -a $LOGFILE
+ echo "Terminating linuxmuster-reset session at `date`" | tee -a $LOGFILE
  echo "#####################################################################" | tee -a $LOGFILE
  rm -f $locker $HOSTLIST $ROOMLIST
  exit "$RC"
@@ -208,18 +208,22 @@ call_script() {
  local trigger="$2"
  local hostlist="$(echo $3 | sed -e 's| |,|g')"
  local script="$SCRIPTSDIR/$(echo $target | tr A-Z a-z)_on_off.sh"
- local RC="0"
+ local RCTMP="0"
  echo | tee -a $LOGFILE
  echo " * $target $(echo $trigger | tr a-z A-Z)" | tee -a $LOGFILE
  echo "   -> $(echo $hostlist | sed -e 's|,|\n   -> |g')" | tee -a $LOGFILE
- $script --trigger=$trigger --hostlist=$hostlist 2>> $LOGFILE 1>> $LOGFILE ; RC="$?"
- if [ "$RC" = "0" ]; then
+ $script --trigger=$trigger --hostlist=$hostlist 2>> $LOGFILE 1>> $LOGFILE ; RCTMP="$?"
+ if [ "$RCTMP" = "0" ]; then
   echo "   OK!"
  else
   echo "   FAILED!"
+  RC="1"
  fi
+ return "$RCTMP"
 }
 
+
+RC="0"
 
 # do internet reset
 # hosts to trigger on
@@ -241,10 +245,11 @@ if [ "$START_LINUXMUSTER" = "yes" ]; then
  # hosts to trigger off
  intranet_off="$(grep ^[A-Za-z0-9] $HOSTLIST | awk '{ print $1 " " $3 }' | grep -i " off" | awk '{ print $1 }')"
  [ -n "$intranet_off" ] && call_script Intranet off "$intranet_off"
- 
+
 else
 
- echo "Skipping intranet reset."
+ echo | tee -a $LOGFILE
+ echo " * Skipping intranet reset." | tee -a $LOGFILE
 
 fi
 
@@ -262,7 +267,8 @@ if [ -n "$uf_active" ]; then
 
 else
 
- echo "Skipping urlfilter reset."
+ echo | tee -a $LOGFILE
+ echo " * Skipping urlfilter reset." | tee -a $LOGFILE
 
 fi
 
@@ -292,12 +298,16 @@ if [ -s "$ROOMLIST" -a -n "$kill" ]; then
     get_login_by_id $user_id
     teacher=$RET
     if check_teacher $teacher; then
-     echo "  * WARNING: Finishing test of teacher $teacher in room $r!" | tee -a $LOGFILE
-     echo "    For detailed output of sophomorix-teacher see $LOGFILE!"
-     sophomorix-teacher --teacher $teacher --room $r --exam --collect 2>> $LOGFILE 1>> $LOGFILE
+     echo " * WARNING: Terminating ongoing exam of teacher $teacher in room $r!" | tee -a $LOGFILE
+     if sophomorix-teacher --teacher $teacher --room $r --exam --collect 2>> $LOGFILE 1>> $LOGFILE; then
+      echo "   For detailed output of sophomorix-teacher see $LOGFILE!"
+     else
+      echo "   sophomorix-teacher failed! See $LOGFILE for details."
+      RC="1"
+     fi
     fi
    fi
-   echo "  * WARNING: I'm killing an active lession in room $r!" | tee -a $LOGFILE
+   echo " * WARNING: I'm killing an active lession in room $r!" | tee -a $LOGFILE
    rm -f $roomfile
   fi
  
@@ -313,5 +323,8 @@ if ! ps ax | grep nscd | grep -v grep &> /dev/null; then
 fi
 
 
-exit_script 0
-
+if [ "$RC" != "0" ]; then
+ echo | tee -a $LOGFILE
+ echo "Terminated with error(s)!" | tee -a $LOGFILE
+fi
+exit_script "$RC"
