linuxmuster-base (1.0-8) testing; urgency=low
  * added Aptitude::Recommends-Important "false"; to apt.conf to prevent
    aptitude from automatically installing packages recommends
  * added target directory test to linuxmuster-backup
  * changed "create mask" and "directory mask" to "force create mode" and
    "force directory mode" for netlogon, pgm and cdrom shares in smb.conf
  * added --drop --dbname=database as parameters to linuxmuster-mysql to
    be able to drop databases by name directly
  * making /etc/linuxmuster/backup.conf and /etc/default/linuxmuster-base
    executable that they can be parsed by per scripts
  * various optimations concerning to ldap database queries
  * added logging of user's realname, primary group and ip address to samba-userlog

linuxmuster-base (1.0-7) testing; urgency=low

  * added FIREWALLTEST variable to dist.conf
  * intranet_on_off.sh is now aborting when internal firewall is not running
  * added backports pinning for rrdtool and librrds-perl to apt preferences

M    share/config/dist.conf
M    share/scripts/helperfunctions.sh
M    share/scripts/intranet_on_off.sh
M    debian/postinst
M    debian/changelog
A    var/config-dynamic/60_nagios
A    var/config-dynamic/60_nagios/prepatch
M    var/config-dynamic/15_ldap/smb.conf
M    var/config-dynamic/00_stop-services/prepatch
M    var/config-static/etc/apt/preferences
M    var/config-static/etc/apt/apt.conf
M    sbin/samba-userlog
M    sbin/linuxmuster-mysql
M    sbin/linuxmuster-backup
M    sbin/linuxmuster-setup

diff --git a/sbin/linuxmuster-backup b/sbin/linuxmuster-backup
--- a/sbin/linuxmuster-backup
+++ b/sbin/linuxmuster-backup
@@ -122,7 +122,7 @@ echo "$mypid" > $mypidfile
 
 # exit with error
 error() {
-	echo "An error occured! Exiting!"
+	echo "$1 Exiting!"
 	rm $mypidfile
 	exit 1
 } # error
@@ -130,7 +130,9 @@ error() {
 
 # create mountpoint if necessary
 [ -d "$mountpoint" ] || mkdir -p $mountpoint
-
+if [ ! -d "$mountpoint" ]; then
+	error "Mountpoint $mountpoint does not exist!"
+fi 
 
 # check if backupdevice is already mounted
 if mount | grep "$backupdevice" | grep -q "$mountpoint"; then
@@ -147,7 +149,8 @@ case $restoremethod in
     hd)
 	if [ -z "$mounted" ]; then
 	    echo "Trying to mount $backupdevice on $mountpoint ..."
-	    mount $backupdevice $mountpoint || error
+	    mount $backupdevice $mountpoint || error "Cannot mount $backupdevice!"
+	    mounted=yes
 	fi
 	rtypeparam="-i"
 	target=$mountpoint/$isoprefix/$bfolder
@@ -156,7 +159,8 @@ case $restoremethod in
     nfs)
 	if [ -z "$mounted" ]; then
 	    echo "Trying to mount $backupdevice on $mountpoint ..."
-	    mount -t nfs -o rsize=8192,wsize=8192 $backupdevice $mountpoint || error
+	    mount -t nfs -o rsize=8192,wsize=8192 $backupdevice $mountpoint || error "Cannot mount $backupdevice!"
+	    mounted=yes
 	fi
 	rtypeparam="-n $backupdevice"
 	target=$isoprefix/$bfolder
@@ -168,7 +172,12 @@ case $restoremethod in
 	;;
 
 esac
-[ -z "$mounted" ] && echo "$backupdevice successfully mounted on $mountpoint!"
+
+if [ -n "$mounted" ]; then
+	echo "$backupdevice successfully mounted on $mountpoint!"
+else
+	error "$backupdevice not mounted!"
+fi
 
 
 # storing runlevel
@@ -332,6 +341,10 @@ fi
 
 # create backup folder if necessary
 [ -d "$mountpoint/$isoprefix/$bfolder/cache" ] || mkdir -p $mountpoint/$isoprefix/$bfolder/cache
+if [ ! -d "$mountpoint/$isoprefix/$bfolder/cache" ]; then
+	[ -d "$mountpoint/$isoprefix/$bfolder" ] && rm -rf $mountpoint/$isoprefix/$bfolder
+	error "Mountpoint $mountpoint/$isoprefix/$bfolder/cache does not exist!"
+fi 
 
 
 # starting mondoarchive
