linuxmuster-base/trunk mit branches/testing zusammengeführt.

diff --git a/sbin/linuxmuster-reset b/sbin/linuxmuster-reset
--- a/sbin/linuxmuster-reset
+++ b/sbin/linuxmuster-reset
@@ -3,8 +3,11 @@
 # linuxmuster-reset-rooms
 # resets the internet, intranet, webfilter, lession state of rooms/hosts
 #
-# 29.01.2008
-# Thomas Schmitt <schmitt@lmz-bw.de>
+# Thomas Schmitt
+# <schmitt@lmz-bw.de>
+# GPL V3
+#
+# $Id$
 #
 
 
@@ -46,12 +49,12 @@ usage() {
   echo
   echo "--room : reset all hosts of this room."
   echo "--host : reset only this specific host."
-  echo "--all  : reset all rooms and hosts defined in $ROOMDEFAULTS."
+  echo "--all  : reset all rooms and hosts defined in $ROOMDEFAULTS_TEMP."
   echo "--kill : kill the room's active lession, if there is one (optional)."
   echo "         Use this with care!"
   echo
   echo "Note: --room and --host are using default values if room/host is not"
-  echo "      defined in $ROOMDEFAULTS."
+  echo "      defined in $ROOMDEFAULTS_TEMP."
   exit_script
 }
 
@@ -65,7 +68,7 @@ usage() {
 
 # check if $ROOMDEFAULTS exists
 if [ ! -e "$ROOMDEFAULTS" ]; then
-	echo "Fatal: File $ROOMDEFAULTS not found!"
+	echo "Fatal: File $ROOMDEFAULTS_TEMP not found!"
 	exit_script
 fi
 
@@ -81,19 +84,24 @@ echo "#####################################################################" | t
 echo "Starting linuxmuster-reset session at `date`" | tee -a $LOGFILE
 echo | tee -a $LOGFILE
 
+# first convert all input files to lower case
+ROOMDEFAULTS_TEMP=/var/tmp/room_defaults.$$
+WIMPORTDATA_TEMP=/var/tmp/workstations.$$
+grep -v ^# $ROOMDEFAULTS | tr A-Z a-z > $ROOMDEFAULTS_TEMP
+grep -v ^# $WIMPORTDATA | tr A-Z a-z > $WIMPORTDATA_TEMP
 
 # create resetlist
 if [ -n "$all" ]; then
-	resetlist=`awk '{ print $1 }' $ROOMDEFAULTS`
+	resetlist=`awk '{ print $1 }' $ROOMDEFAULTS_TEMP`
 elif [ -n "$host" ]; then
-	resetlist=$host
+	resetlist=`echo $host | tr A-Z a-z`
 elif [ -n "$room" ]; then
-	resetlist=$room
-	# fetch hosts for this room and look for host definitions in $ROOMDEFAULTS
-	hosts=`grep ^$room\; $WIMPORTDATA | cut -f2 -d";"`
+	resetlist=`echo $room | tr A-Z a-z`
+	# fetch hosts for this room and look for host definitions in $ROOMDEFAULTS_TEMP
+	hosts=`grep ^$room\; $WIMPORTDATA_TEMP | cut -f2 -d";"`
 	if [ -n "$hosts" ]; then
 		for h in $hosts; do
-			grep -q ^$h[[:space:]] $ROOMDEFAULTS && resetlist="$resetlist $h"
+			grep -q ^$h[[:space:]] $ROOMDEFAULTS_TEMP && resetlist="$resetlist $h"
 		done
 	fi
 fi
@@ -102,15 +110,12 @@ fi
 # check resetlist for valid entries and clean it up
 for r in $resetlist; do
 
-	# skip comments
-	[ "${r:0:1}" = "#" ] && continue
-
 	# skip rooms or hosts which are named "default"
 	[ "$r" = "default" ] && continue
 
-	# check if room/host is defined in $WIMPORTDATA
-	if ! grep -v ^# $WIMPORTDATA | grep -qw $r; then
-		echo "Room or host $r is not defined in $WIMPORTDATA! Skipping $r!" | tee -a $LOGFILE
+	# check if room/host is defined in $WIMPORTDATA_TEMP
+	if ! grep -qw $r $WIMPORTDATA_TEMP; then
+		echo "Room or host $r is not defined in $WIMPORTDATA_TEMP! Skipping $r!" | tee -a $LOGFILE
 		continue
 	fi
 
@@ -141,8 +146,8 @@ webfilter_default=on
 roomfile_prefix="/var/run/schulkonsole/room_"
 
 
-# read default values from $ROOMDEFAULTS if set
-if line=`grep ^default[[:space:]] $ROOMDEFAULTS`; then
+# read default values from $ROOMDEFAULTS_TEMP if set
+if line=`grep ^default[[:space:]] $ROOMDEFAULTS_TEMP`; then
 	internet_default=`echo $line | awk '{ print $2 }'`
 	intranet_default=`echo $line | awk '{ print $3 }'`
 	webfilter_default=`echo $line | awk '{ print $4 }'`
@@ -171,7 +176,7 @@ $SCRIPTSDIR/check_urlfilter.sh && uf_active=yes
 for r in $resetlist; do
 
 	# check if $r is a room
-	if grep -q ^$r\; $WIMPORTDATA; then
+	if grep -q ^$r\; $WIMPORTDATA_TEMP; then
 		room=yes; typ=room; typm=Room
 	else
 		room=no; typ=host; typm=Host
@@ -180,24 +185,24 @@ for r in $resetlist; do
 	echo
 	echo "Processing $typ $r ..." | tee -a $LOGFILE
 
-	# check if room/host is defined in $ROOMDEFAULTS
-	if ! grep -q ^$r[[:space:]] $ROOMDEFAULTS; then
+	# check if room/host is defined in $ROOMDEFAULTS_TEMP
+	if ! grep -q ^$r[[:space:]] $ROOMDEFAULTS_TEMP; then
 		# if not use default values
-		echo "  * $typm $r is not defined in $ROOMDEFAULTS! Using default values!" | tee -a $LOGFILE
+		echo "  * $typm $r is not defined in $ROOMDEFAULTS_TEMP! Using default values!" | tee -a $LOGFILE
 		internet=$internet_default
 		intranet=$intranet_default
 		webfilter=$webfilter_default
 	else
-		# else read room/host values from $ROOMDEFAULTS
-		line=`grep ^$r[[:space:]] $ROOMDEFAULTS`
+		# else read room/host values from $ROOMDEFAULTS_TEMP
+		line=`grep ^$r[[:space:]] $ROOMDEFAULTS_TEMP`
 		internet=`echo $line | awk '{ print $2 }'`
 		intranet=`echo $line | awk '{ print $3 }'`
 		webfilter=`echo $line | awk '{ print $4 }'`
 	fi
 
 	if [ "$room" = "yes" ]; then
-		# fetch room's hostlist from $WIMPORTDATA
-		hostlist=`grep ^$r\; $WIMPORTDATA | cut -f2 -d\;`
+		# fetch room's hostlist from $WIMPORTDATA_TEMP
+		hostlist=`grep ^$r\; $WIMPORTDATA_TEMP | cut -f2 -d\;`
 		hostlist=`echo $hostlist | sed -e 's/ /,/g'`
 		# skips if hostlist is empty
 		if [ -z "$hostlist" ]; then
@@ -280,4 +285,5 @@ echo | tee -a $LOGFILE
 echo "Ending linuxmuster-reset session at `date`" | tee -a $LOGFILE
 echo "#####################################################################" | tee -a $LOGFILE
 
-rm -f $locker
+rm -f $locker $ROOMDEFAULTS_TEMP $WIMPORTDATA_TEMP
+
diff --git a/sbin/linuxmuster-setup b/sbin/linuxmuster-setup
--- a/sbin/linuxmuster-setup
+++ b/sbin/linuxmuster-setup
@@ -3,10 +3,13 @@
 #
 # Thomas Schmitt <schmitt@lmz-bw.de>
 # GPL-2
+#
+# $Id$
+#
 
 # check debian version
-if [ "$(cat /etc/debian_version)" != "4.0" ]; then
-	echo "This is not Debian 4.0 Etch. Please upgrade your system!"
+if ! grep -q 5\.0\.[1-9] /etc/debian_version; then
+	echo "This is not Debian 5.0.x Lenny. Please upgrade your system!"
 	exit 1
 fi
 
@@ -31,10 +34,25 @@ usage() {
   exit 1
 }
 
+# mount installation cdrom
+mount_cdrom() {
+ local device=$1
+ [ -n "$device" ] && device="/dev/$device"
+ mount $device /cdrom &> /dev/null
+ if grep -q "[op][pa][e][nd]ML Linux" /cdrom/.disk/info &> /dev/null; then
+  return 0
+ else
+  umount /cdrom &> /dev/null
+  return 1
+ fi
+}
+
 [[ "$opt" = "--first" || "$opt" = "--modify" ]] || usage
 
 # look if we were on first boot
 if [ -e /etc/inittab.real ]; then
+
+  firstboot=yes
 
   # reread inittab
   mv /etc/inittab.real /etc/inittab
@@ -62,67 +80,102 @@ fi
 
 # logfile
 logfile=$LOGDIR/setup.log
-echo >> $LOGDIR/setup.log
-echo "####################################################" >> $LOGDIR/setup.log
-echo "Setup session started at `date`" >> $LOGDIR/setup.log
-date >> $LOGDIR/setup.log
-echo "####################################################" >> $LOGDIR/setup.log
+echo >> $logfile
+chmod 600 $logfile
+echo "####################################################" >> $logfile
+echo "Setup session started at `date`" >> $logfile
+date >> $logfile
+echo "####################################################" >> $logfile
 
 echo "Logging output to $logfile ..."
 echo
 
 # reconfiguring package to have all templates
-dpkg-reconfigure linuxmuster-base | tee -a $LOGDIR/setup.log
+dpkg-reconfigure linuxmuster-base | tee -a $logfile
 
 # calling as base-config late command
 case $opt in
 
   --first)
 
+    # copy apt configs if not on first boot
+    if [ -z "$firstboot" ]; then
+     cp /etc/apt/sources.list /etc/apt/sources.list.orig
+     cp -a $STATICTPLDIR/etc/apt/* /etc/apt
+    fi
+
     # turn shadow passwords on
-    shadowconfig on | tee -a $LOGDIR/setup.log
+    shadowconfig on | tee -a $logfile
 
     # add cyrus user
-    id cyrus &> /dev/null || useradd -c "Cyrus Mailsystem User" -d /var/spool/cyrus -g mail -m -r -s /bin/sh cyrus | tee -a $LOGDIR/setup.log
+    id cyrus &> /dev/null || useradd -c "Cyrus Mailsystem User" -d /var/spool/cyrus -g mail -m -r -s /bin/sh cyrus | tee -a $logfile
 
-    # load cdrom tray
+    # mount cdrom
     if grep -q ^"deb cdrom" /etc/apt/sources.list; then
-	eject -t
-	mount /cdrom
+	eject -t &> /dev/null
+	for i in "" scd0 scd1 scd2; do
+	 if mount_cdrom "$i"; then
+	  if stringinstring scd "$i"; then
+	   rm -f /dev/cdrom /dev/dvd
+	   ln -s /dev/$i /dev/cdrom
+	   ln -s /dev/$i /dev/dvd
+	   cp /etc/fstab /etc/fstab.linuxmuster-setup.first
+	   grep -v cdrom /etc/fstab.linuxmuster-setup.first > /etc/fstab
+	   echo "/dev/$i /media/cdrom0 udf,iso9660 user,noauto 0 0" >> /etc/fstab
+	  fi
+	  cdrom_mounted=yes
+	  break
+	 fi
+	done
+	if [ -z "$cdrom_mounted" ]; then
+	 echo "Fatal: Cannot mount install cd!"
+	 exit 1
+	fi
     fi
 
     # install paedml release key
     [ -e /cdrom/paedml-release.asc ] && apt-key add /cdrom/paedml-release.asc
 
     # check tasks
-    for i in common server desktop imaging-linbo imaging-tivoli imaging-rembo; do
+    for i in common server desktop imaging-linbo imaging-rembo; do
       if [ ! -s "/usr/share/linuxmuster/tasks/$i" ]; then
         echo "Error: Taskfile $i not found!"
         exit 1
       fi
     done
 
-		# tweak system time due to debian bug #531569 (http://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg654573.html)
-		date 0101000009
-
     # force apt to do ugly things during upgrade
     echo 'DPkg::Options {"--force-confold";"--force-confdef";"--force-bad-verify";"--force-overwrite";};' > /etc/apt/apt.conf.d/99upgrade
 
-    # check if linuxmuster-indexpage is installable
+    # check for installable non-free packages
     indexpage=`aptitude search linuxmuster-indexpage`
+    templatespaedml=`aptitude search linuxmuster-schulkonsole-templates-paedml`
 
     # tweaking buggy sophomorix, install postgresql first
-    DEBIAN_FRONTEND=noninteractive aptitude -y install postgresql | tee -a $LOGDIR/setup.log
-    #DEBIAN_FRONTEND=noninteractive aptitude -y install postgresql-8.1 | tee -a $LOGDIR/setup.log
+    DEBIAN_FRONTEND=noninteractive aptitude -y install postgresql | tee -a $logfile
+    #DEBIAN_FRONTEND=noninteractive aptitude -y install postgresql-8.1 | tee -a $logfile
 
     # installing depending task
     for i in common server; do
       task=`cat /usr/share/linuxmuster/tasks/$i`
-      DEBIAN_FRONTEND=noninteractive aptitude -y install $task | tee -a $LOGDIR/setup.log
+      DEBIAN_FRONTEND=noninteractive aptitude -y install $task | tee -a $logfile
     done
 
+    # reconfigure locale settings
+    for i in locale.gen timezone; do
+     conf=/etc/$i
+     cp $STATICTPLDIR/$conf $conf
+    done
+    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
+    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure tzdata
+    install-keymap /usr/share/keymaps/i386/qwertz/de-latin1-nodeadkeys.kmap.gz
+    kmapmd5=`md5sum /etc/console-setup/boottime.kmap.gz | awk '{ print $1 }' 2> /dev/null`
+    sed -e "s/^BOOTTIME_KMAP_MD5=.*/BOOTTIME_KMAP_MD5=\"$kmapmd5\"/" $STATICTPLDIR/etc/default/console-setup > /etc/default/console-setup
+    /etc/init.d/console-setup restart
+
     # install indexpage if available
-    [ -n "$indexpage" ] && aptitude -y install linuxmuster-indexpage | tee -a $LOGDIR/setup.log
+    [ -n "$indexpage" ] && aptitude -y install linuxmuster-indexpage | tee -a $logfile
+    [ -n "$templatespaedml" ] && aptitude -y install linuxmuster-schulkonsole-templates-paedml | tee -a $logfile
 
     # remove upgrade cheat
     rm /etc/apt/apt.conf.d/99upgrade
@@ -133,8 +186,8 @@ case $opt in
 
     # check for installed flag
     if [ ! -e "$INSTALLED" ]; then
-      echo "Linux-Musterloesung isn't installed yet!" | tee -a $LOGDIR/setup.log
-      echo "You have to use the command linuxmuster-setup --first!" | tee -a $LOGDIR/setup.log
+      echo "Linux-Musterloesung isn't installed yet!" | tee -a $logfile
+      echo "You have to use the command linuxmuster-setup --first!" | tee -a $logfile
       exit 1
     fi
 
@@ -142,7 +195,7 @@ case $opt in
 
 	# fetch external network configuration from ipcop
 	if ping -c 2 $ipcopip &> /dev/null; then
-		echo "Reading IPCop's external network configuration ..." | tee -a $LOGDIR/setup.log
+		echo "Reading IPCop's external network configuration ..." | tee -a $logfile
 		tmpdir=/var/tmp/ipcop.$$
 		mkdir -p $tmpdir
 		get_ipcop /var/ipcop/ethernet/settings $tmpdir/settings
@@ -176,13 +229,13 @@ case $opt in
 
 	else
 
-		echo "Cannot connect to IPCop!" | tee -a $LOGDIR/setup.log
+		echo "Cannot connect to IPCop!" | tee -a $logfile
 		exit 1
 
 	fi
 
     # reading current debconf values
-    echo "Reading current configuration values ..." | tee -a $LOGDIR/setup.log
+    echo "Reading current configuration values ..." | tee -a $logfile
     for i in country state location workgroup servername domainname schoolname dsluser dslpasswd smtprelay \
              internsubrange fwconfig externtype externip externmask gatewayip dnsforwarders imaging; do
       RET=`echo get linuxmuster-base/$i | debconf-communicate`
@@ -206,8 +259,8 @@ case $opt in
 esac
 
 # backup debconf db
-backup_file /var/cache/debconf/config.dat | tee -a $LOGDIR/setup.log
-backup_file /var/cache/debconf/passwords.dat | tee -a $LOGDIR/setup.log
+backup_file /var/cache/debconf/config.dat | tee -a $logfile
+backup_file /var/cache/debconf/passwords.dat | tee -a $logfile
 chmod 600 $BACKUPDIR/var/cache/debconf/passwords.dat-$DATETIME.gz
 
 # ask questions
@@ -228,4 +281,6 @@ fi
 
 # call configuration patch script
 $SCRIPTSDIR/linuxmuster-patch $opt
+
+chmod 600 $logfile
 
