* wimport.sh: Mehr Konsolenausgaben von sophomorix-workstations. * Internes Firewallskript:   * komplett überarbeitet für verbesserte Performanz,   * beim Herunterfahren werden die iptables-Regeln nach /var/cache/linuxmuster/iptables gesichert   * und beim Booten aus dieser Datei wieder geladen, was die Bootzeit signifikant verkürzt.

diff --git a/etc/init.d/linuxmuster-base b/etc/init.d/linuxmuster-base
--- a/etc/init.d/linuxmuster-base
+++ b/etc/init.d/linuxmuster-base
@@ -13,7 +13,7 @@
 ### END INIT INFO
 
 # Thomas Schmitt <tschmitt@linuxmuster.de>
-# 20.09.2012
+# 05.01.2013
 
 # source default settings
 [ -f /etc/default/linuxmuster-base ] && . /etc/default/linuxmuster-base
@@ -31,186 +31,250 @@
 [ -e "$BLOCKEDHOSTSINTRANET" ] || touch $BLOCKEDHOSTSINTRANET
 
 # read mac addresses
-macs=`grep -v ^# $WIMPORTDATA | awk -F\; '{ print $4 }' -`
+macs="$(grep -v ^# $WIMPORTDATA | awk -F\; '{ print $4 }' | tr a-z A-Z)"
 
-stop_firewall() {
+# file which saves the fw rules
+IPTRULES="$CACHEDIR/iptables"
+
+# check if we were called on boot
+echo "$0" | grep -q ^/etc/rc && ONBOOT=yes
 
 
-  echo -n "Stopping internal firewall"
+# save rules and flush iptables rules completely
+flush_fw() {
 
-  # clear chains
+ # do only if there are rules
+ if iptables -L IN-$IFACE &> /dev/null; then
+  # save rules first
+  iptables-save > "$IPTRULES" ; RC="$?"
+  # remove it all
   iptables -D INPUT -i $IFACE -j IN-$IFACE
   iptables -F IN-$IFACE
   iptables -X IN-$IFACE
+  if [ "$RC" != "0" ]; then
+   echo " ... failed to save rules!"
+   echo
+   rm -f "$IPTRULES"
+   exit "$RC"
+  fi
+ else
+  rm -f "$IPTRULES"
+ fi
 
+} # flush_fw
+
+
+stop_firewall() {
+
+  echo -n "Stopping internal firewall"
+  flush_fw
   echo "."
 
-}
+} # stop_firewall
+
+
+create_mac_rules() {
+ 
+ local RULE
+ 
+ # write allowed ports rules
+ if [ -f "$ALLOWEDPORTS" ]; then
+  while read proto portrange; do
+   [ "${proto:0:1}" = "#" ] && continue
+   [[ -z "$portrange" || -z "$proto" ]] && continue
+   portrange=${portrange//,/ }
+   for p in $portrange; do
+    for m in $macs; do
+     validmac $m || continue
+      RULE="-A IN-$IFACE -p $proto -m mac --mac-source $m -m $proto --dport $p -j ACCEPT"
+      if [ -n "$INSERT_NR" ]; then
+       sed "${INSERT_NR}i\
+$RULE" -i "$IPTRULES"
+      else
+       echo "$RULE" >> "$IPTRULES"
+      fi
+    done
+   done
+  done <$ALLOWEDPORTS
+ fi
+
+ # strip blocked mac addresses from list
+ for m in `cat $BLOCKEDHOSTSINTRANET`; do
+  macs=${macs/$m/}
+ done
+
+ # write blocked ports rules
+ if [ -f "$BLOCKEDPORTS" ]; then
+  while read proto portrange; do
+   [ "${proto:0:1}" = "#" ] && continue
+   [[ -z "$portrange" || -z "$proto" ]] && continue
+   portrange=${portrange//,/ }
+   for p in $portrange; do
+    for m in $macs; do
+     validmac $m || continue
+      RULE="-A IN-$IFACE -p $proto -m mac --mac-source $m -m $proto --dport $p -j ACCEPT"
+      if [ -n "$INSERT_NR" ]; then
+       sed "${INSERT_NR}i\
+$RULE" -i "$IPTRULES"
+      else
+       echo "$RULE" >> "$IPTRULES"
+      fi
+    done
+   done
+  done <$BLOCKEDPORTS
+ fi
+
+} # create_mac_rules
+
+# create all rules from scratch and write them to file
+create_rulesfile() {
+
+ # write header
+ cat > "$IPTRULES" <<EOF
+# Generated by linuxmuster-base on `date`
+*filter
+:INPUT ACCEPT [0:0]
+:FORWARD ACCEPT [0:0]
+:OUTPUT ACCEPT [0:0]
+:IN-$IFACE - [0:0]
+-A INPUT -i $IFACE -j IN-$IFACE
+-A IN-$IFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
+-A IN-$IFACE -s $ipcopip/32 -j ACCEPT
+-A IN-$IFACE ! -s $internalnet/$internmask_short -j ACCEPT
+EOF
+
+ # write mandatory open ports rules
+ if [ -f "$BASEPORTS" ]; then
+  while read proto portrange; do
+   [ "${proto:0:1}" = "#" ] && continue
+   [[ -z "$portrange" || -z "$proto" ]] && continue
+   portrange=${portrange//,/ }
+   for p in $portrange; do
+    echo "-A IN-$IFACE -p tcp -m tcp --dport $p -j ACCEPT" >> "$IPTRULES"
+   done
+  done <$BASEPORTS
+ fi
+
+ create_mac_rules
+
+ # footer
+ cat >> "$IPTRULES" <<EOF
+-A IN-$IFACE -p icmp -m icmp --icmp-type 8 -j ACCEPT
+-A IN-$IFACE -j REJECT --reject-with icmp-port-unreachable
+COMMIT
+# Completed on `date`
+EOF
+
+} # create_rulesfile
+
 
 start_firewall() {
 
-    # don't do this when reloading
-    if [ -z "$reload" ]; then
+ echo -n "Starting internal firewall"
+ 
+ if [ -n "$ONBOOT" -a -s "$IPTRULES" ]; then
+  echo -n " on boot, loading saved file"
+ else
+  create_rulesfile
+ fi
+ 
+ if ! iptables-restore < "$IPTRULES"; then
+  echo " ... failed to load $IPTRULES!"
+  echo
+  exit 1
+ fi
+ 
+ echo "."
 
-      # clear chains if there are any
-      if iptables -L IN-$IFACE &> /dev/null; then stop_firewall; fi
-
-      echo -n "Starting internal firewall"
-
-      # create new chains
-      iptables -N IN-$IFACE
-      iptables -A INPUT -i $IFACE -j IN-$IFACE
-
-      # accept stated connections
-      iptables -A IN-$IFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
-
-      # accept from ipcop
-      iptables -A IN-$IFACE -s $ipcopip/32 -j ACCEPT
-
-      # accept from anywhere except lan
-      iptables -A IN-$IFACE ! -s $internalnet/$internmask_short -j ACCEPT
-
-      # read mandatory open ports
-      if [ -f "$BASEPORTS" ]; then
-        while read proto portrange; do
-          [ "${proto:0:1}" = "#" ] && continue
-          [[ -z "$portrange" || -z "$proto" ]] && continue
-          portrange=${portrange//,/ }
-          for p in $portrange; do
-            iptables -A IN-$IFACE -p $proto --dport $p -j ACCEPT
-          done
-        done <$BASEPORTS
-      fi
-
-    fi # don't do this when reloading
-
-    # read allowed ports
-    if [ -f "$ALLOWEDPORTS" ]; then
-      while read proto portrange; do
-        [ "${proto:0:1}" = "#" ] && continue
-        [[ -z "$portrange" || -z "$proto" ]] && continue
-        portrange=${portrange//,/ }
-        for p in $portrange; do
-          for m in $macs; do
-            if [ -n "$reload" ]; then
-              validmac $m && iptables -I IN-$IFACE $insert_nr -p $proto -m mac --mac-source $m --dport $p -j ACCEPT
-            else
-              validmac $m && iptables -A IN-$IFACE -p $proto -m mac --mac-source $m --dport $p -j ACCEPT
-            fi
-          done
-        done
-      done <$ALLOWEDPORTS
-    fi
-
-    # strip blocked mac addresses
-    for m in `cat $BLOCKEDHOSTSINTRANET`; do
-      macs=${macs/$m/}
-    done
-
-    # allow blocked ports
-    if [ -f "$BLOCKEDPORTS" ]; then
-      while read proto portrange; do
-        [ "${proto:0:1}" = "#" ] && continue
-        [[ -z "$portrange" || -z "$proto" ]] && continue
-        portrange=${portrange//,/ }
-        for p in $portrange; do
-          for m in $macs; do
-            if [ -n "$reload" ]; then
-              validmac $m && iptables -I IN-$IFACE $insert_nr -p $proto -m mac --mac-source $m --dport $p -j ACCEPT
-            else
-              validmac $m && iptables -A IN-$IFACE -p $proto -m mac --mac-source $m --dport $p -j ACCEPT
-            fi
-          done
-        done
-      done <$BLOCKEDPORTS
-    fi
-
-    # don't do this when reloading
-    if [ -z "$reload" ]; then
-
-      # ICMP: accept ping
-      iptables -A IN-$IFACE -p icmp --icmp-type 8 -j ACCEPT
-
-      # reject the rest
-      iptables -A IN-$IFACE -j REJECT
-
-      echo "."
-
-    fi
-
-}
+} # start_firewall
 
 
+# reload fw by modifying rules file
 reload_firewall() {
 
-    echo -n "Reloading internal firewall"
+ echo -n "Reloading internal firewall"
 
-    # fetch all macs which have rules
-    active_macs=`iptables -L IN-$IFACE | grep MAC | awk '{ print $7 }' | sort -u`
+ # save rules
+ iptables-save > "$IPTRULES" ; RC="$?"
+ if [ "$RC" != "0" ]; then
+  echo " ... failed to save rules!"
+  echo
+  rm -f "$IPTRULES"
+  exit "$RC"
+ fi
 
-    # delete rules with macs not in wimport_data
-    for m in $active_macs; do
-      if ! stringinstring $m "$macs"; then
-        active_macs=${active_macs/$m/}
-        rules_to_delete=`iptables -L IN-$IFACE --line-numbers | grep $m | awk '{ print $1 }' | sort -rn`
-        for r in $rules_to_delete; do
-          iptables -D IN-$IFACE $r
-        done
-      fi
-    done
-    strip_spaces "$active_macs"
-    active_macs="$RET"
+ # fetch all macs which have rules
+ active_macs="$(grep -w mac "$IPTRULES" | awk '{ print $8 }' | sort -u)"
 
-    # filter out macs which have already rules
-    if [ -n "$active_macs" ]; then
+ # remove rules with macs not in workstations file
+ local m
+ for m in $active_macs; do
+  stringinstring $m "$macs" && continue
+  active_macs=${active_macs/$m/}
+  grep -v "$m" "$IPTRULES" > "$IPTRULES.tmp"
+  mv "$IPTRULES.tmp" "$IPTRULES"
+ done
+ strip_spaces "$active_macs"
+ active_macs="$RET"
 
-      for m in $macs; do
-        stringinstring $m "$active_macs" && macs=${macs/$m/}
-      done
-      strip_spaces "$macs"
-      macs="$RET"
+ # filter out macs which have already rules
+ if [ -n "$active_macs" ]; then
+  for m in $macs; do
+   stringinstring $m "$active_macs" && macs=${macs/$m/}
+  done
+  strip_spaces "$macs"
+  macs="$RET"
+ fi
 
-    fi
+ # insert rules for new macs if there are any
+ if [ -n "$macs" ]; then
+  # compute line number to insert before
+  INSERT_NR="$(grep -m1 -n -w icmp "$IPTRULES" | awk -F\: '{ print $1 }')"
+  # exit if line number cannot be determined
+  if [ -n "$INSERT_NR" ]; then
+   create_mac_rules
+  else
+   echo " ... error in $IPTRULES!"
+   echo
+   [ -e "$IPTRULES" ] && mv "$IPTRULES" "$IPTRULES.failed"
+   exit 1
+  fi
+ fi
 
-    # start firewall if there are any macs without rules remaining
-    if [ -n "$macs" ]; then
+ # load fw rules files
+ if ! iptables-restore < "$IPTRULES"; then
+  echo " ... failed to load $IPTRULES!"
+  echo
+  exit 1
+ fi
 
-      # rule nr for inserting
-      insert_nr=`iptables -L IN-$IFACE --line-numbers | grep -m1 MAC | awk '{ print $1 }'`
+ echo "."
 
-      # start
-      reload=yes
-      start_firewall
-
-    fi
-
-    echo "."
-
-}
+} # reload_firewall
 
 
 case "$1" in
 
-  start)
-    start_firewall
-    ;;
+ start)
+  start_firewall
+  ;;
 
-  stop)
-    stop_firewall
-    ;;
+ stop)
+  stop_firewall
+  ;;
 
-  reload)
-    reload_firewall
-    ;;
+ restart)
+  stop_firewall
+  start_firewall
+  ;;
 
-  restart|force-reload)
-    stop_firewall
-    start_firewall
-    ;;
+ reload|force-reload)
+  reload_firewall
+  ;;
 
-  *)
-    echo "Usage: $0 <start|stop|reload|restart|force-reload>"
-    ;;
+ *)
+  echo "Usage: $0 <start|stop|reload|restart|force-reload>"
+  ;;
 
 esac
 
