linuxmuster-base (1.2-16) testing; urgency=low
  * fixed: index.html was not patched if servername or domainname were
    changed by linuxmuster-setup
  * fixed: ipcop root password was asked during linuxmuster-setup

linuxmuster-base (1.2-15) testing; urgency=low

  * moved /usr/share/doc/linuxmuster-base/registry-patches to
    /usr/share/linuxmuster-base
  * added windows batch script machine-passwd.bat and mtaman.exe to
    registry-patches
  * reparing permissions in netlogondir during postinst


linuxmuster-base (1.2-14) testing; urgency=low

  * fixed empty imaging variable in postinst

linuxmuster-base (1.2-13) testing; urgency=low

  * added pre-xfer and post-xfer parameters to linbo-upload section in
    rsyncd.conf, according to linbo revision 119
  * added backports pinning for rsync to /etc/apt/preferences

linuxmuster-base (1.2-12) testing; urgency=low

  * added hwclock --utc at the end of linuxmuster-setup
  * stopping and starting nscd service at beginning and end of import_workstations
  * added daily cron job to clean login cache from dead logins
  * added Win2k/XP registry patches necessary for joining windows domain
  * linking /usr/share/doc/linuxmuster-base/registry-patches to
    administrator's home

linuxmuster-base (1.2-11) testing; urgency=low

  * added code to handle acceptation of sun java license if tivoli
    has been chosen as imaging system
  * added sun java license templates (stolen from sun-java5-bin debian package)
  * linuxmuster-setup is now using the config.csv.tpl from tpmfos package
  * minor modifications due to changes in tpmfos 5.1.0.3_paedML3 and
    tpmfos-derby 10.3.1.4_paedML2 concerning service startup variables
    and their handling in linuxmuster-setup

linuxmuster-base (1.2-10) testing; urgency=low

  * minor optimations in wimport-linbo.sh and import_workstations
  * fixed lockfile handling in samba-userlog
  * minor optimations in linuxmuster-config and linuxmuster-patch
    concerning to imaging system configuration and installation

M    share/scripts/linuxmuster-patch
M    share/scripts/wimport_linbo.sh
M    share/scripts/linuxmuster-config
A    share/registry-patches
A    share/registry-patches/Win2k-XP
A    share/registry-patches/Win2k-XP/machine-passwd.bat
A    share/registry-patches/Win2k-XP/win2k-xp-clients_ohne_imaging-patch.reg
AM   share/registry-patches/Win2k-XP/mtaman.exe
A    share/registry-patches/Win2k-XP/README
A    share/registry-patches/Win98
A    share/registry-patches/Win98/Win9X-CacheHandling.reg
A    share/registry-patches/Win98/dont_esc_logon.reg
A    share/registry-patches/Win98/disable_pwl_caching.reg
M    debian/postinst
M    debian/changelog
M    debian/rules
M    debian/templates
A    debian/cron.daily
D    doc/registry-patches
M    var/config-dynamic/46_tpmfos/prepatch
M    var/config-dynamic/99_start-services/prepatch
M    var/config-dynamic/23_apache2/prepatch
M    var/config-dynamic/00_ipcop/prepatch
M    var/config-static/etc/apt/preferences
D    var/config-static/etc/init.d/tpmfos-derby
M    var/config-static/etc/rsyncd.conf
M    sbin/import_workstations

diff --git a/share/scripts/linuxmuster-config b/share/scripts/linuxmuster-config
--- a/share/scripts/linuxmuster-config
+++ b/share/scripts/linuxmuster-config
@@ -4,6 +4,7 @@
 . /usr/share/debconf/confmodule
 
 db_version 2.0
+db_capb backup
 db_title "Linux-Musterloesung 3.0"
 
 PRIORITY="critical"
@@ -221,8 +222,73 @@ if [ -n "$IMG_CHOICES" ]; then
 	db_subst linuxmuster-base/imaging img_desc $IMG_DESC
 	db_input $PRIORITY linuxmuster-base/imaging || true
 	db_go
+	db_get linuxmuster-base/imaging || true
+	imaging=$RET
 else
 	db_set linuxmuster-base/imaging $imaging || true
+fi
+
+# present and let accept or decline sun java license if necessary
+# stolen from sun-java5-bin package
+if [ "$imaging" = "tivoli" ]; then
+
+	license=sun-dlj-v1-1
+
+	db_get shared/accepted-$license
+	if [ "$RET" = "true" ]; then
+
+		echo "$license license has already been accepted" >&2
+
+	else
+
+		STATE=1
+		while true; do
+    			case "$STATE" in
+				0)  # ensure going back from license presentment is harmless
+					STATE=1 
+					continue
+					;;
+				1)  # present license
+					db_fset shared/present-$license seen false
+					if ! db_input critical shared/present-$license ; then
+						echo "$license license could not be presented!"
+						echo "Please start linuxmuster-setup $1 again to repeat the configuration!" >&2
+						exit 2
+					fi
+					db_fset shared/accepted-$license seen false
+					if ! db_input critical shared/accepted-$license ; then
+						echo "$license agree question could not be asked!"
+						echo "Please start linuxmuster-setup $1 again to repeat the configuration!" >&2
+						exit 2
+					fi
+					;;
+				2)  # determine users' choice
+					db_get shared/accepted-$license
+					if [ "$RET" = "true" ]; then
+						# license accepted
+						break
+					fi
+					;;
+				3)  # user has confirmed declining license
+					echo "You did not accept the $license license!" >&2
+					echo "Please start linuxmuster-setup $1 again to repeat the configuration!" >&2
+					exit 1
+					;;
+				*)  # unknown state
+					echo "$license license state unknown: $STATE!" >&2
+					echo "Please start linuxmuster-setup $1 again to repeat the configuration!" >&2
+					exit 2
+					;;
+			esac
+			if db_go; then
+				STATE=$(($STATE + 1))
+			else
+				STATE=$(($STATE - 1))
+			fi
+		done
+
+	fi
+
 fi
 
 
